# Generated by Django 2.0.1 on 2019-01-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('old_rover', '0002_addrover'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrover',
            name='subteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='old_rover.Member', verbose_name='member of rover'),
        ),
    ]
