# Generated by Django 2.0.1 on 2019-01-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('old_rover', '0004_auto_20190114_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrover',
            name='Member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_of', to='old_rover.Member', verbose_name='Member name'),
        ),
    ]
