# Generated by Django 2.0.1 on 2019-01-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('old_rover', '0007_remove_addrover_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rover_years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_of', to='old_rover.AddRover', verbose_name='member name'),
        ),
    ]
